export const GET_EARTHQUAKE_DATA = "GET_EARTHQUAKE_DATA"
export const FETCH_FROM_API = "FETCH_FROM_API"
export const NEW_FETCH_FREQUENCY = "NEW_FETCH_FREQUENCY"
export const SORT_EARTHQUAKE_DATA = "SORT_EARTHQUAKE_DATA"
export const REVERSE_EARTHQUAKE_DATA = "REVERSE_EARTHQUAKE_DATA";
